import express from 'express';
import multer from 'multer';
import ExcelJS from 'exceljs';
import {parse} from 'csv-parse/sync';
import QRCode from 'qrcode';
import {randomUUID,randomBytes} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
const app=express(), port=Number(process.env.PORT||4173), root=import.meta.dirname;
const dataFile=process.env.DATA_FILE||path.join(root,'data/attendees.json');
const seed=[];
fs.mkdirSync(path.dirname(dataFile),{recursive:true});
let rows=fs.existsSync(dataFile)?JSON.parse(fs.readFileSync(dataFile,'utf8')):seed;
function save(next){fs.writeFileSync(dataFile+'.tmp',JSON.stringify(next,null,2));fs.renameSync(dataFile+'.tmp',dataFile);rows=next;}
if(!fs.existsSync(dataFile))save(rows);
app.use(express.json({limit:'1mb'}));
app.use('/api',(_req,res,next)=>{res.set('Cache-Control','no-store');next()});
const sessions=new Set();
function staff(req,res,next){const token=(req.headers.cookie||'').split('; ').find(x=>x.startsWith('staff='))?.slice(6);if(!sessions.has(token))return res.status(401).json({error:'Enter the staff PIN to continue.'});next();}
app.post('/api/login',(req,res)=>{if(req.body.pin!==(process.env.STAFF_PIN||'2468'))return res.status(401).json({error:'That PIN is incorrect.'});const token=randomBytes(32).toString('hex');sessions.add(token);res.cookie('staff',token,{httpOnly:true,sameSite:'strict',maxAge:43200000});res.json({ok:true})});
app.post('/api/logout',(req,res)=>{const token=(req.headers.cookie||'').split('; ').find(x=>x.startsWith('staff='))?.slice(6);sessions.delete(token);res.clearCookie('staff');res.json({ok:true})});
app.get('/api/attendees',(_req,res)=>res.json(rows.map(({id,name,signedAt})=>({id,name,signedAt}))));
app.get('/api/staff',staff,(_req,res)=>res.json(rows));
app.get('/api/attendees/:id',(req,res)=>{const person=rows.find(r=>r.id===req.params.id);if(!person)return res.status(404).json({error:'Attendee not found. Please select your name again.'});const {id,name,license,ce,paid,signedAt}=person;res.json({id,name,license,ce,paid,signedAt})});
app.post('/api/sign',(req,res)=>{
 const {id,name,license,ce,paid,signature}=req.body;
 if(typeof signature!=='string'||!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(signature)||signature.length>700000)return res.status(400).json({error:'Please add your signature.'});
 let person=rows.find(r=>r.id===id);
 if(id&&!person)return res.status(404).json({error:'Attendee not found. Please select your name again.'});
 if(person?.signedAt)return res.status(409).json({error:'You are already signed in. Please see the registration desk for changes.'});
 if(typeof name!=='string'||!name.trim()||name.length>150||typeof license!=='string'||!license.trim()||license.length>80)return res.status(400).json({error:'Enter your name and license number (or N/A).'});
 if(!['YES','NO','?'].includes(ce)||!['YES','NO','N/A',''].includes(paid))return res.status(400).json({error:'Choose a valid CE credit and payment status.'});
 if(rows.some(r=>r.id!==id&&r.name.toLowerCase()===name.trim().toLowerCase()))return res.status(409).json({error:'That name is already on the list. Please select it or see the registration desk.'});
 if(!id)person={id:randomUUID(),walkIn:true};
 const details={name:name.trim(),license:license.trim(),ce,paid};
 const signed={...person,...details,signature,signedAt:new Date().toISOString(),attendeeConfirmedDetails:details};
 save(id?rows.map(r=>r.id===id?signed:r):[...rows,signed]);res.json({ok:true,name:signed.name});
});
app.patch('/api/staff/:id',staff,(req,res)=>{const person=rows.find(r=>r.id===req.params.id);if(!person)return res.status(404).json({error:'Attendee not found.'});const {ce,paid,license}=req.body;if(!['YES','NO','?'].includes(ce)||!['YES','NO','N/A',''].includes(paid)||typeof license!=='string'||license.length>80)return res.status(400).json({error:'Invalid attendee details.'});save(rows.map(r=>r.id===person.id?{...r,ce,paid,license}:r));res.json({ok:true})});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});
const cell=v=>v==null?'':typeof v==='object'?(v.text||v.result||v.richText?.map(t=>t.text).join('')||''):String(v);
app.post('/api/import',staff,upload.single('file'),async(req,res)=>{try{if(!req.file)throw Error('Choose a CSV or .xlsx file.');let matrix;if(req.file.originalname.toLowerCase().endsWith('.csv'))matrix=parse(req.file.buffer,{bom:true,skip_empty_lines:true});else if(req.file.originalname.toLowerCase().endsWith('.xlsx')){const wb=new ExcelJS.Workbook();await wb.xlsx.load(req.file.buffer);matrix=[];wb.worksheets[0].eachRow(r=>matrix.push(Array.from({length:r.cellCount},(_,i)=>cell(r.getCell(i+1).value))));}else throw Error('Use a CSV or .xlsx file.');const headers=matrix.shift()?.map(v=>String(v).trim().toLowerCase());const idx=label=>headers?.indexOf(label);if(idx('name')<0||idx('license number')<0)throw Error('The first row must include Name and License Number. Download the template for an example.');const incoming=matrix.filter(r=>r.some(v=>String(v).trim())).map((r,i)=>{const get=label=>String(r[idx(label)]||'').trim();const name=get('name'),license=get('license number'),ce=get('ce credit').toUpperCase()||'?',paid=get('paid (y/n)').toUpperCase();if(!name||name.length>150||license.length>80||!['YES','NO','?'].includes(ce)||!['YES','NO','N/A',''].includes(paid))throw Error(`Check row ${i+2}: name, CE credit (YES/NO/?), or paid status (YES/NO/N/A).`);return {id:randomUUID(),name,license,ce,paid,signature:null,signedAt:null,walkIn:false};});if(!incoming.length||incoming.length>2000)throw Error('Upload between 1 and 2,000 attendees.');const seen=new Set(rows.map(r=>r.name.toLowerCase()));const added=[];for(const r of incoming){if(!seen.has(r.name.toLowerCase())){added.push(r);seen.add(r.name.toLowerCase())}}save([...rows,...added]);res.json({message:`Added ${added.length} attendees. Skipped ${incoming.length-added.length} existing or duplicate names. Existing signatures were kept.`});}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/template',staff,async(_req,res)=>{const wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('Attendees');ws.addRow(['Name','License Number','CE Credit','Paid (Y/N)']);ws.addRow(['Dr. Example Name','OPC 1234','YES','']);ws.columns.forEach(c=>c.width=24);res.attachment('attendee-template.xlsx');res.send(Buffer.from(await wb.xlsx.writeBuffer()))});
app.get('/api/connection',staff,async(_req,res)=>{const addresses=Object.values(os.networkInterfaces()).flat().filter(x=>x.family==='IPv4'&&!x.internal).map(x=>x.address);const address=addresses.find(x=>x.startsWith('192.168.'))||addresses.find(x=>x.startsWith('10.'))||addresses[0]||'localhost';const url=`http://${address}:${port}`;res.json({url,qr:await QRCode.toDataURL(url,{width:240,margin:1,color:{dark:'#092b46',light:'#ffffff'}})})});
app.get('/api/backup',staff,(_req,res)=>{res.attachment('sign-in-backup.json').json(rows)});
app.use(express.static(path.join(root,'dist')));
app.get('/{*splat}',(_req,res)=>res.sendFile(path.join(root,'dist/index.html')));
app.use((err,_req,res,_next)=>{console.error(err.message);res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'The upload must be under 5 MB.':'The request could not be saved. Please try again.'})});
app.listen(port,'0.0.0.0',()=>console.log(`Retina check-in: http://localhost:${port}`));
